name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checks:
    name: 🧪 Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: install latest version of corepack
        run: npm i -g corepack@latest
      - name: enable corepack
        run: corepack enable
      - name: install dependencies
        run: pnpm i
      - name: check format
        run: pnpm format-check
      - name: build
        run: pnpm build
      - name: lint
        run: pnpm lint
      - name: typecheck
        run: pnpm typecheck

  deploy-docker:
    name: 🐳 Deploy Docker Image
    runs-on: ubuntu-latest
    environment: dockerhub
    needs: checks
    if: github.ref == 'refs/heads/main' && success()
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    env:
      VERSION: latest
      IMAGE_NAME: zacowan/lucky-bot-bot-server
    steps:
      - uses: actions/checkout@v4
      # Set up Docker Buildx for multi-platform support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          platforms: ${{ matrix.platform }}
